[package]
name = "fusion-sequencer"
version = "0.1.0"
edition = "2021"

[dependencies]
ruint = { version = "1.10.1", default-features = false, features = ["serde"] }
anyhow = "1.0.66"
clap = { version = "4.1.4", features = ["derive"] }
ethers = { version = "2" }
futures = "0.3.26"
log = "0.4.17"
tarpc = { version = "0.31", features = ["full"] }
tokio = { version = "1.25.0", features = ["macros", "sync", "rt-multi-thread"] }
fusion-l1 = { path = "../l1-verifier/out/bindings" }
fusion-api = { path = "../fusion-api" }
fusion-config = { path = "../fusion-config" }
fusion-prover = { path = "../fusion-prover" }
fusion-rpc = { path = "../fusion-rpc" }
fusion-state= { path = "../fusion-state" }
fusion-types = { path = "../fusion-types" }

serde_cbor = { version = "0.11.2" }

[dev-dependencies]
anvil = { git = "https://github.com/foundry-rs/foundry" }
hex = "0.4.3"
